import express from "express";
import Blog from "../models/Blog.js";
import Discussion from "../models/Discussion.js";
import MedicalRecord from "../models/MedicalRecord.js";
import Order from "../models/Order.js";
import Pet from "../models/Pet.js";
import Product from "../models/Product.js";
import Review from "../models/Review.js";
import Vaccination from "../models/Vaccination.js";
import adminRoutes from "./adminRoutes.js";
import aiRoutes from "./aiRoutes.js";
import appointmentRoutes from "./appointmentRoutes.js";
import blogRoutes from "./blogRoutes.js";
import adoptionRoutes from "./adoptionRoutes.js";
import contactRoutes from "./contactRoutes.js";
import authRoutes from "./authRoutes.js";
import crudRoutes from "./crudRoutes.js";
import matchRoutes from "./matchRoutes.js";
import messageRoutes from "./messageRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import { createResourceController } from "../controllers/resourceController.js";
import petRoutes from "./petRoutes.js";
import communityRoutes from "./communityRoutes.js";
import marketRoutes from "./marketRoutes.js";
import medicalRoutes from "./medicalRoutes.js";
import vaccinationRoutes from "./vaccinationRoutes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/uploads", uploadRoutes);
router.use("/pets", petRoutes);
router.use("/medical-records", crudRoutes(createResourceController(MedicalRecord, ["pet", "veterinarian"])));
router.use("/vaccinations", crudRoutes(createResourceController(Vaccination, ["pet"])));
router.use("/appointments", appointmentRoutes);
router.use("/products", crudRoutes(createResourceController(Product, ["seller"])));
router.use("/orders", crudRoutes(createResourceController(Order, ["user", "items.product"])));
router.use("/match", matchRoutes);
router.use("/adoptions", adoptionRoutes);
router.use("/contact", contactRoutes);
router.use("/blogs", blogRoutes);
router.use("/discussions", crudRoutes(createResourceController(Discussion, ["author", "replies.user"])));
router.use("/notifications", notificationRoutes);
router.use("/reviews", crudRoutes(createResourceController(Review, ["user"])));
router.use("/messages", messageRoutes);
router.use("/admin", adminRoutes);
router.use("/community", communityRoutes);
router.use("/market", marketRoutes);
router.use("/medical-records", medicalRoutes);
router.use("/vaccinations", vaccinationRoutes);
router.use("/ai", aiRoutes);

export default router;
